### ISSUE TITLE
[ImportError] behavior module name conflicts with pyecore.behavior

### ISSUE THREAD

**Issue by cgava** [cgava/pyEcoreCapella#1]
detected on commit: https://github.com/cgava/pyEcoreCapella/commit/68a03703771034306f4a824429e1e3087aa1c87b

```
Traceback (most recent call last):
  File "capella2python/tests/test.py", line 7, in <module>
    import pyEcoreCapella.activity as Activity
  File "capella2python/pyEcoreCapella/activity/__init__.py", line 2, in <module>
    from .activity import getEClassifier, eClassifiers
  File "capella2python/pyEcoreCapella/activity/activity.py", line 7, in <module>
    from behavior import AbstractBehavior
  File "GitWS-Community/pyecore/pyecore/behavior.py", line 36, in <module>
    from . import ecore
ImportError: attempted relative import with no known parent package
```

**Comment by cgava** [comment]
Problem is solved by the two following steps

1. rename behavior (to ebehavior for example) in pyecore
2. create __init__.py at the root of pyEcoreCapella that imports all the symbols defined in packages

**Comment by cgava** [comment]
happens also with re package
